### ISSUE TITLE
Manually create PR's instead of bitbucket-cli

### ISSUE THREAD

**Issue by berry807** [BasSmeets/multigit#1]
We could also parse the git output to get the bitbucket 'create PR' link and then automatically open this link in the default system browser.

For Mac OS `open "https://google.nl"`
For Windows `start "https://google.nl"`

But it's maybe better to use a cross-platform solution with python for example: `python -m webbrowser "https://google.nl"`

This way we keep the freedom to edit the PR with titles, descriptions, screenshots etc.

**Comment by BasSmeets** [comment]
automatic pr created was introduced in v2.0
making this request obsolete :)
